### PR TITLE
Initial attempt to make Source generic over JsonRpcClient

### PR DESCRIPTION
**Pull request by 0xprames**
Draft PR for #65 attempting to make Source generic over `impl ethers::providers::JsonRpcClient` to allow for both a Ws and HttpProvider

This currently doesn't compile because the current implementation route makes the `Dataset` trait non-object safe!

```
error[E0038]: the trait `types::datatypes::scalar::Dataset` cannot be made into an object
   --> crates/freeze/src/types/datatypes/multi.rs:54:49
    |
54  |     fn datasets(&self) -> HashMap<Datatype, Box<dyn Dataset>> {
    |                                                 ^^^^^^^^^^^ `types::datatypes::scalar::Dataset` cannot be made into an object
    |
note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
   --> crates/freeze/src/types/datatypes/scalar.rs:177:14
    |
148 | pub trait Dataset: Sync + Send {
    |           ------- this trait cannot be made into an object...
...
177 |     async fn collect_chunk(
    |              ^^^^^^^^^^^^^ ...because method `collect_chunk` has generic type parameters
...
196 |     async fn collect_block_chunk(
    |              ^^^^^^^^^^^^^^^^^^^ ...because method `collect_block_chunk` has generic type parameters
...
207 |     async fn collect_transaction_chunk(
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^ ...because method `collect_transaction_chunk` has generic type parameters
...
218 |     async fn collect_address_chunk(
    |              ^^^^^^^^^^^^^^^^^^^^^ ...because method `collect_address_chunk` has generic type parameters
    = help: consider moving `collect_chunk` to another trait
    = help: consider moving `collect_block_chunk` to another trait
    = help: consider moving `collect_transaction_chunk` to another trait
    = help: consider moving `collect_address_chunk` to another trait
```

any pointers/corrections or simplifications here or via another PR welcome! I'm happy to close this out, wanted to take a stab at seeing how this would look

### CODE REVIEW

**Review by gakonst — COMMENTED** [review]
This should work by refactoring `struct Fetcher` to be generic over `M: Middleware`, and have that propagate to `Source`, instead of generalizing over the _transport_

**Comment by 0xprames** [comment]
I see yeah - that makes sense, just went through the `ethers-middleware` crate.
Where im still a bit confused is this:

> and have that propagate to Source

Trying to understand how to get it such that we don't have to generalize `Source` over anything since that seems to give us the above-mentioned compiler errors.  Basically how to avoid this:

```
pub struct Source <M> where M: Middleware {
fetcher: Arc<Fetcher<M>>, // how to get away from specifying the generic in the attribute here, such that Source can be declared without a generic?
// other attributes

}

pub struct Fetcher<M> where M: Middleware {
// other attributes
provider: M
}
```

**Comment by gakonst** [comment]
Define `Fetcher<M> { provider: M }` and then _only_ in `impl<M: Middleware> Fetcher { ...}` do you restrict the trait. This ensures that you can still use `struct Source<M> { fetcher: Fetcher<M> }` without having to do `Source<M: Middleware> { fetcher: Fetcher<M> }`

**Comment by 0xprames** [comment]
yeah you're right that doing what you mentioned would make `Source<M>`generic  without needing `Source<M:Middelware>` but what I see from this current iteration of the PR is

`Source<M>` as a generic seems to breaks the "object-safe" trait contract set by `Dataset`, specifically in how its returned [here](https://github.com/paradigmxyz/cryo/blob/5e4c4e911d37d53342ad38b5f947b8e1ec9b41a7/crates/freeze/src/types/datatypes/scalar.rs#L115)

because the corresponding trait functions would need to be defined as such (IIUC):
```
async fn collect_chunk<M>(
        &self,
        chunk: &Chunk,
        source: &Source,
        source: &Source<M>,
```

there seem to be some [workarounds](https://www.possiblerust.com/pattern/3-things-to-try-when-you-can-t-make-a-trait-object), including using an `Enum` type instead of a generic, but that's a bit more of a structural change - so i wanted to kickstart a discussion.

Also - if im misunderstanding the pasted compiler error/the link  above, let me know. I could be wrong in how I understand the error.

**Comment by 0xprames** [comment]
going to close this out for now

dont want to leave a stale PR draft hanging, not sure how to work around what I mentioned above without reworking either the Dataset trait or making Source accept an enum Fetcher/Provider, which would significantly change the code (matches everywhere).

Im also not sure adding WS is a super critical feature, since cryo functions fine as is, so I dont think restructuring the code is worth it here.

**Pull request closed without merging**
