### PR TITLE
Implement optional retry logic for queries

### PR DESCRIPTION
**Pull request by ipatka**
Add exponential backoff retries to block fetching. This helps when running big batches like contract datasets

This adds a new cli arg for max retries. 3 is reasonable

```
Acquisition Options:
  -l, --requests-per-second <limit>  Ratelimit on requests per second
      --max-retries <R>              Enable exponential backoff retries on errors
      --max-concurrent-requests <M>  Global number of concurrent requests
      --max-concurrent-chunks <M>    Number of chunks processed concurrently
  -d, --dry                          Dry run, collect no data

```

Modified sources.rs to either use retry logic or original logic
```
    async fn execute_request<T, A: Action>(&self, mut action: A) -> Result<T>
    where
        A: Action<Item = T, Error = ProviderError>,
    {
        let retry_strategy = self.retry_strategy.clone();
        let result = match retry_strategy {
            Some(retry_strategy) => Self::map_err(Retry::spawn(retry_strategy, action).await),
            None => Self::map_err(action.run().await),
        };
        Ok(result?)
    }
```

### CODE REVIEW

**Comment by sslivkoff** [comment]
+💯 for `--max-retries`, this will be a huge UX boost and fix a lot of ratelimit-related issues

two things

1. for implementation some of this functionality is already present in the ethers.rs [`RetryClient`](https://docs.rs/ethers-providers/latest/ethers_providers/struct.RetryClient.html). is there an advantage to rolling custom logic instead of just using `RetryClient`? would really like to keep `Fetcher` and associated functions as simple as possible + minimize future maintenance requirements
2. it would be good to have a default greater than zero here. 3 would be good as you say. that will make the default experience smoother for newer non-power users. if users want to disable retries they can do `--max-retries 0`

**Comment by ipatka** [comment]
> +💯 for `--max-retries`, this will be a huge UX boost and fix a lot of ratelimit-related issues
> 
> two things
> 
>     1. for implementation some of this functionality is already present in the ethers.rs [`RetryClient`](https://docs.rs/ethers-providers/latest/ethers_providers/struct.RetryClient.html). is there an advantage to rolling custom logic instead of just using `RetryClient`? would really like to keep `Fetcher` and associated functions as simple as possible + minimize future maintenance requirements
> 
>     2. it would be good to have a default greater than zero here. 3 would be good as you say. that will make the default experience smoother for newer non-power users. if users want to disable retries they can do `--max-retries 0`

1 - I hadn't seen the ethers retry client. Will try to use that instead and see how it goes!

2 - Agree that sounds like better UX. will update

**Comment by ipatka** [comment]
Integrated the ethers retyclient in this branch. created a separate PR to compare the implementations:
https://github.com/paradigmxyz/cryo/pull/60

i think it looks a lot cleaner. but it behaves a bit differently from the on in this PR. converting both to drafts while I do some testing

**Comment by ipatka** [comment]
closing in favor of #60

**Pull request closed without merging**
