### PR TITLE
Add exponential backoff to queries using RetryClient

### PR DESCRIPTION
**Pull request by ipatka**
Similar to https://github.com/paradigmxyz/cryo/pull/59 but using the default ethers retry client (looks a lot cleaner)

```
Acquisition Options:
  -l, --requests-per-second <limit>  Ratelimit on requests per second
      --max-retries <R>              Specify max retries on provider errors [default: 10]
      --initial-backoff <B>          Specify initial backoff for retry strategy (ms) [default: 500]
      --max-concurrent-requests <M>  Global number of concurrent requests
      --max-concurrent-chunks <M>    Number of chunks processed concurrently
  -d, --dry                          Dry run, collect no data
```

New provider

```
    let provider =
        Provider::<RetryClient<Http>>::new_client(&rpc_url, args.max_retries, args.initial_backoff)
            .map_err(|_e| ParseError::ParseError("could not connect to provider".to_string()))?;
```

### CODE REVIEW

**Comment by sslivkoff** [comment]
looking great

wdyt the defaults should be? max-retries=10 could be fine, unless that means that a broken node won't be detected for something like 2**10 * 0.5 = 512 seconds. but maybe the `RetryClient` is smart enough to stop early if the node is messed up. for reference [these](https://github.com/alchemyplatform/alchemy-sdk-js/blob/2ad5254686c290b2b739e64a37d13417f835493a/src/internal/backoff.ts#L3) are the defaults used by the alchemy sdk (initial=1000ms max_retries=5)

**Comment by ipatka** [comment]
> looking great
> 
> wdyt the defaults should be? max-retries=10 could be fine, unless that means that a broken node won't be detected for something like 2**10 * 0.5 = 512 seconds. but maybe the `RetryClient` is smart enough to stop early if the node is messed up. for reference [these](https://github.com/alchemyplatform/alchemy-sdk-js/blob/2ad5254686c290b2b739e64a37d13417f835493a/src/internal/backoff.ts#L3) are the defaults used by the alchemy sdk (initial=1000ms max_retries=5)

5 & 1000 (or maybe 500) seems reasonable. 10 & 500 came from the default values in the retryclient docs. Will update the defaults!

**Comment by ipatka** [comment]
@sslivkoff defaults updated and marking this one ready for review. will close the other one

**Comment by sslivkoff** [comment]
looks great

**Pull request merged**
