### PR TITLE
Fix multi block argument and add some unit tests

### PR DESCRIPTION
**Pull request by ipatka**
Multi block commands were not working due to a conflict in clap settings which caused commands like this to fail with a parser error:
```
cryo txs --blocks 16000000 16000001 16000002
```

The `allow_hyphen_values` conflicted with the multiple arguments parsing for block values.
https://github.com/paradigmxyz/cryo/blob/5c060155a5b85ae3db5e3cebe269323d180771d8/crates/cli/src/args.rs#L17

~~This PR adds a value terminator which is required to end the block list~~

This PR changes blocks to expect single input, wrapped in quotes

```
cryo txs --blocks "16000000 16000001 16000002"
```

Also added some unit tests while i was looking around

### CODE REVIEW

**Comment by ipatka** [comment]
looks like formatter is failing but not sure how to fix locally, running `cargo fmt` in root directory

**Comment by sslivkoff** [comment]
pr looks good

the `allow_hyphen_values` conflict with `num_args` is unfortunate. hyphen args is necessary for using things like `--blocks -1000:latest` which is a fairly important use case. but needing to use multiple blocks is another important use case

the semicolon syntax is not the end of the world but it's a bit jarring and it will be inconsistent with the usage of cryo's other multi-arg options

I think in a more perfect world the parsing of `--blocks` would be conditional. something like "if there are multiple args, make it `allow_hyphen_values=true`, but if there's just a single arg, make it `allow_hyphen_values=false`". not sure if there's a reasonable way to implement this in clap tho

some options here in order from easiest to hardest
1. `--blocks 16000000 16000001 16000002;`
2. `--blocks "16000000 16000001 16000002"`
3. do a multistage parse, try to parse with `allow_hyphen_values=true num_args=1`, if that fails, try with `allow_hyphen_values=false num_args=1..`
4. implement some custom clap args thing

I'm thinking that option 2 would be best because it is most consistent with other cli tools and with cryo's other multi-arg options

**Comment by sslivkoff** [comment]
to pass format checks need to use `cargo +nightly fmt`. this should be added to the README...

**Comment by ipatka** [comment]
i like option 2 as well, should just involve a minor change to arg parsing, will try it out

**Comment by sslivkoff** [comment]
ok yea try it out. I think that would be the best short term solution

longer term we can explore more complex parsing options for making it so the quotations are optional

**Comment by ipatka** [comment]
Converted to draft while I look into the alternative methods to the terminator

**Comment by sslivkoff** [comment]
awesome stuff

**Pull request merged**
