### PR TITLE
fallback to multiple `eth_getTransactionReceipt` calls if `eth_getBlockReceipts` is not present

### LINKED ISSUE #93: About use of `eth_getBlockReceipts` JSON RPC for `cryo txs`
**Is your feature request related to a problem? Please describe.**

Use of new JSON RPC API - `eth_getBlockRecipts` broke some scripts that worked before, especially for other chains that forked ethereum's execution clients (apparently geth) complying with most of JSON RPC specs but not very up-to-date. Tested on optimism & arbitrum, for official mainnet sequencer rpc endpoints.

```
$ cast rpc eth_getBlockReceipts 0x6A31748 --rpc-url https://mainnet.optimism.io
Error:
(code: -32001, message: rpc method is not whitelisted, data: None)

$ cast rpc eth_getBlockReceipts 0x896C1CB --rpc-url https://arb1.arbitrum.io/rpc
Error:
(code: -32601, message: the method eth_getBlockReceipts does not exist/is not available, data: None)
```

This problem occured after merge of #89 which was introduced to filter out reverted txs (#46). While this feature will be indeed crucial and very useful for majority of cryo users, I have some doubts about its current specification and implementation.

First, `eth_getBlockReceipts` was standarized recently. While almost every execution clients implement the method on ethereum, I found most of other evm-like chains and its execution clients do not have the method. The only chain I found implementing this method aside from ethereum was bnb.

Second, in terms of clarifying which data the user wants to extract, the `status`, `gas_used` and `transaction_index` etc. are actually properties of `receipts`, not `tx`s. If only raw transaction data is needed for certain analysis, fetching receipts causes unnecessary overhead. (Still, I think there are very few analysis can be done with tx data without receipts) This is important because while there were receipt related properties on transaction schema before, it was considered optional, but current implementation for `--exclude-failed` seems to force fetching receipts and fails if fetching receipt errors whether the option is supplied or not.

**Describe the solution you'd like**

1. implement workaround when `eth_getBlockReceipts` errors - iterating over transaction hashes and call `eth_getTransactionReceipt`. This will emit much more RPC calls than the original solution, but is considerable if it is better than failing.
2. When `eth_getBlockReceipts` errors leave receipt field None, and if `--exclude-failed` option was supplied, panic on `transform` step

Also, this RPC method will have to be mentioned on README.md as used method for fetching txs data.

**Describe alternatives you've considered**

- separating `cryo txs` from `cryo receipts` - but this would not help much for users to overcome this issue but increase product's complexity.

**Additional context**
- [eth_getBlockReceipts spec](https://github.com/ethereum/execution-apis/blob/main/src/eth/block.yaml#L89), merged on [Aug 15](https://github.com/ethereum/execution-apis/pull/438), spec introduced on [Mar 26](https://github.com/ethereum/execution-apis/issues/393)

If specs are fixed, I would be happy if I can submit a PR to implement the fix.

### PR DESCRIPTION
**Pull request by cool-mestorf**
## Motivation

resolves #93

## Solution

To add a robust fallback mechanism for `eth_getBlockReceipts`, which had become outdated after recent updates, I created an extension trait `FetcherExt`. This trait is implemented for `Arc<Fetcher<P>>` and allows us to use reference of rate-limited providers over multiple tasks. I welcome any feedback on how to test this implementation effectively.

command tested:
```
$ cryo txs -b 145968168:145968169 --rpc https://arb1.arbitrum.io/rpc
```

before:
```
...
collecting data
───────────────
started at 2023-11-01 15:54:01.276
   done at 2023-11-01 15:54:01.639


error summary
─────────────
(errors in 1 chunks)
- Failed to get block: (code: -32601, message: the method eth_getBlockReceipts does not exist/is not available, data: None) (1x)


collection summary
──────────────────
- total duration: 0.362 seconds
- total chunks: 1
    - chunks errored:   1 / 1 (100.0%)
    - chunks skipped:   0 / 1 (0.0%)
    - chunks collected: 0 / 1 (0.0%)
- blocks collected: 0
    - blocks per second: 0.0
    - blocks per minute: 0.0
    - blocks per hour:   0.0
    - blocks per day:    0.0
```

after:
```
...
collecting data
───────────────
started at 2023-11-01 15:43:00.476
   done at 2023-11-01 15:43:01.056


collection summary
──────────────────
- total duration: 0.579 seconds
- total chunks: 1
    - chunks errored:   0 / 1 (0.0%)
    - chunks skipped:   0 / 1 (0.0%)
    - chunks collected: 1 / 1 (100.0%)
- blocks collected: 1
    - blocks per second:    1.7
    - blocks per minute:  103.5
    - blocks per hour:  6,207.1
    - blocks per day: 148,991.2
```

## PR Checklist

-   [ ] Added Tests
-   [x] Added Documentation
-   [ ] Breaking changes

### CODE REVIEW

**Comment by cool-mestorf** [comment]
Well actually I tried it first but it was impossible because - for concurrent `eth_getTransactionReceipt` calls I needed to clone reference of fetcher (self) to send through async tasks, but it wouldn't be possible as long as `Fetcher` is wrapped inside `Arc`. The original implementation also held `Arc<Fetcher>` so I approached to define an extension trait and implement it for `Arc<Fetcher>`.

**Comment by sslivkoff** [comment]
ah ok I see. I think that's why the former `get_txs_gas_used` was implemented directly on `Source` instead of `Fetcher`

not 100% sure but I think putting it directly on `Source` would be cleaner than using a new trait. because when we want more concurrent-task-spawn functions like this in the future, we only need to write out the function signature one time, in `Source`'s `impl`. otherwise each signature will appear two times in the file and that's less maintainable if you have 10 such functions

**Comment by cool-mestorf** [comment]
I moved the implementation into `Source`. This would be the first implementation to use a wrapper implementation around `Source` rather than using `source.fetcher` directly, which was why I didn't implement it on `Source` at first time... :)

**Comment by sslivkoff** [comment]
excellent stuff. thanks

feel free to submit more issues but also come check out the TG group where there's lots of cryo discussion https://t.me/paradigm_data

**Pull request merged**
